# .github/workflows/ci-cd.yml
name: Test, Build, and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  # New job to run the automated test suite
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Ensure pytest is installed

      - name: Run Pytest
        run: pytest

  # This job now depends on the 'test' job
  build-and-push:
    needs: test  # This line makes it wait for the 'test' job to succeed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Training Pipeline image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./training.Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/training-pipeline:latest

      - name: Build and push Flask App image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-predictor-app:latest